title: KeLes Coding
description:
# description: ノーコンティニューでクリアしてやるぜ！
author: KeLes
email: leske94@foxmail.com
lang: en
theme: null
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
baseurl: ""
url: "https://keles-coding.github.io"
timezone: Asia/Shanghai
future: true
github_repository_url: "https://github.com/KeLes-Coding/KeLes-Coding.github.io"
github_branch: "main"
orbit_repository_url: "https://github.com/KeLes-Coding/Orbit"
orbit_branch: "main"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: KeLes
      visible: true
  - scope:
      path: ""
    values:
      layout: default

permalink: /posts/:title/

exclude:
  - README.md
