title: KeLes Coding
description:
# description: ノーコンティニューでクリアしてやるぜ！
author: KeLes
email: leske94@foxmail.com
lang: en
theme: null
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
baseurl: ""
url: "https://keles-coding.github.io"
timezone: Asia/Shanghai
future: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: KeLes
      city: "Bermuda Triangle📍"
      visible: true
  - scope:
      path: ""
    values:
      layout: default

permalink: /posts/:title/

exclude:
  - README.md